#!/bin/bash
yum install httpd -y
yum update -y
service httpd start
chkconfig httpd on
echo "<html><body bgcolor="yellow"><h1> Hello World from auto scalling </h1></body></html>" > /var/www/html/index.html
